spring.application.name=shipment-tracker
spring.datasource.url=jdbc:h2:mem:shipmentdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8080
logging.level.com.example.shipmenttracker=DEBUG
logging.level.org.springframework.messaging=DEBUG
jwt.secret=pOS6FqM6f8md4BkVvSlaFAavJCMfftPyR1yY5YVaVwXJgQ8ztJGg2gAWq0x
jwt.expiration=86400000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=engineers.newgeneration@gmail.com
spring.mail.password=ypzdevelkpwlwcvd
spring.mail.from=engineers.newgeneration@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true